//load
export const LOAD_RECORD = "LOAD_RECORD";
export const LOAD_RECORD_PENDING = "LOAD_RECORD_PENDING";
export const LOAD_RECORD_FULFILLED = "LOAD_RECORD_FULFILLED";
export const LOAD_RECORD_REJECTED = "LOAD_RECORD_REJECTED";

//add
export const ADD_RECORD = "ADD_RECORD";
export const ADD_RECORD_PENDING = "ADD_RECORD_PENDING";
export const ADD_RECORD_FULFILLED = "ADD_RECORD_FULFILLED";
export const ADD_RECORD_REJECTED = "ADD_RECORD_REJECTED";

//remove
export const REMOVE_RECORD = "REMOVE_RECORD";
export const REMOVE_RECORD_PENDING = "REMOVE_RECORD_PENDING";
export const REMOVE_RECORD_FULFILLED = "REMOVE_RECORD_FULFILLED";
export const REMOVE_RECORD_REJECTED = "REMOVE_RECORD_REJECTED";

//update
export const UPDATE_RECORD ="UPDATE_RECORD";
export const UPDATE_RECORD_PENDING = "UPDATE_RECORD_PENDING";
export const UPDATE_RECORD_FULFILLED = "UPDATE_RECORD_FULFILLED";
export const UPDATE_RECORD_REJECTED = "UPDATE_RECORD_REJECTED";
